# Generated by Django 3.0 on 2019-12-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20191211_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
